// src/routes/projects/index.svelte
<script lang="ts">
	import { cubicInOut } from 'svelte/easing';
	import { fly } from 'svelte/transition';
	import ProjectCard from '../../components/ProjectCard.svelte';
</script>

<section class="w-full mt-16 md:mt-32">
	<div class="" transition:fly={{ easing: cubicInOut, duration: 500, y: 20 }}>
		<!-- <CollectionHeader link="/posts" label="23 posts" /> -->
		<div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
			<ProjectCard />
			<ProjectCard />
			<ProjectCard />
			<ProjectCard />
			<ProjectCard />
			<ProjectCard />
		</div>
	</div>
</section>

// src/pages/projects/index.tsx
import ProjectCard from "../../components/ProjectCard";
// import ProjectCardSkeleton from '../components/ProjectCardSkeleton';

export default function ProjectsPage() {
  return (
    <div className="w-full my-4 pt-2 pb-10 __mainContent">
      <div className="w-full grid grid-cols-1 sm:grid-cols-2 gap-4">
        <ProjectCard />
        <ProjectCard />
        <ProjectCard />
        <ProjectCard />
        <ProjectCard />
        <ProjectCard />
        <ProjectCard />
        <ProjectCard />
      </div>
    </div>
  );
}
